package mall.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class EbStoreProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public EbStoreProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNull() {
            addCriterion("mer_id is null");
            return (Criteria) this;
        }

        public Criteria andMerIdIsNotNull() {
            addCriterion("mer_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerIdEqualTo(Integer value) {
            addCriterion("mer_id =", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotEqualTo(Integer value) {
            addCriterion("mer_id <>", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThan(Integer value) {
            addCriterion("mer_id >", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mer_id >=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThan(Integer value) {
            addCriterion("mer_id <", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdLessThanOrEqualTo(Integer value) {
            addCriterion("mer_id <=", value, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdIn(List<Integer> values) {
            addCriterion("mer_id in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotIn(List<Integer> values) {
            addCriterion("mer_id not in", values, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdBetween(Integer value1, Integer value2) {
            addCriterion("mer_id between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andMerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mer_id not between", value1, value2, "merId");
            return (Criteria) this;
        }

        public Criteria andImageIsNull() {
            addCriterion("image is null");
            return (Criteria) this;
        }

        public Criteria andImageIsNotNull() {
            addCriterion("image is not null");
            return (Criteria) this;
        }

        public Criteria andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (Criteria) this;
        }

        public Criteria andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (Criteria) this;
        }

        public Criteria andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (Criteria) this;
        }

        public Criteria andSliderImageIsNull() {
            addCriterion("slider_image is null");
            return (Criteria) this;
        }

        public Criteria andSliderImageIsNotNull() {
            addCriterion("slider_image is not null");
            return (Criteria) this;
        }

        public Criteria andSliderImageEqualTo(String value) {
            addCriterion("slider_image =", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageNotEqualTo(String value) {
            addCriterion("slider_image <>", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageGreaterThan(String value) {
            addCriterion("slider_image >", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageGreaterThanOrEqualTo(String value) {
            addCriterion("slider_image >=", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageLessThan(String value) {
            addCriterion("slider_image <", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageLessThanOrEqualTo(String value) {
            addCriterion("slider_image <=", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageLike(String value) {
            addCriterion("slider_image like", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageNotLike(String value) {
            addCriterion("slider_image not like", value, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageIn(List<String> values) {
            addCriterion("slider_image in", values, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageNotIn(List<String> values) {
            addCriterion("slider_image not in", values, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageBetween(String value1, String value2) {
            addCriterion("slider_image between", value1, value2, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andSliderImageNotBetween(String value1, String value2) {
            addCriterion("slider_image not between", value1, value2, "sliderImage");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNull() {
            addCriterion("store_name is null");
            return (Criteria) this;
        }

        public Criteria andStoreNameIsNotNull() {
            addCriterion("store_name is not null");
            return (Criteria) this;
        }

        public Criteria andStoreNameEqualTo(String value) {
            addCriterion("store_name =", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotEqualTo(String value) {
            addCriterion("store_name <>", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThan(String value) {
            addCriterion("store_name >", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameGreaterThanOrEqualTo(String value) {
            addCriterion("store_name >=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThan(String value) {
            addCriterion("store_name <", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLessThanOrEqualTo(String value) {
            addCriterion("store_name <=", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameLike(String value) {
            addCriterion("store_name like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotLike(String value) {
            addCriterion("store_name not like", value, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameIn(List<String> values) {
            addCriterion("store_name in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotIn(List<String> values) {
            addCriterion("store_name not in", values, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameBetween(String value1, String value2) {
            addCriterion("store_name between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreNameNotBetween(String value1, String value2) {
            addCriterion("store_name not between", value1, value2, "storeName");
            return (Criteria) this;
        }

        public Criteria andStoreInfoIsNull() {
            addCriterion("store_info is null");
            return (Criteria) this;
        }

        public Criteria andStoreInfoIsNotNull() {
            addCriterion("store_info is not null");
            return (Criteria) this;
        }

        public Criteria andStoreInfoEqualTo(String value) {
            addCriterion("store_info =", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoNotEqualTo(String value) {
            addCriterion("store_info <>", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoGreaterThan(String value) {
            addCriterion("store_info >", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoGreaterThanOrEqualTo(String value) {
            addCriterion("store_info >=", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoLessThan(String value) {
            addCriterion("store_info <", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoLessThanOrEqualTo(String value) {
            addCriterion("store_info <=", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoLike(String value) {
            addCriterion("store_info like", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoNotLike(String value) {
            addCriterion("store_info not like", value, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoIn(List<String> values) {
            addCriterion("store_info in", values, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoNotIn(List<String> values) {
            addCriterion("store_info not in", values, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoBetween(String value1, String value2) {
            addCriterion("store_info between", value1, value2, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andStoreInfoNotBetween(String value1, String value2) {
            addCriterion("store_info not between", value1, value2, "storeInfo");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNull() {
            addCriterion("bar_code is null");
            return (Criteria) this;
        }

        public Criteria andBarCodeIsNotNull() {
            addCriterion("bar_code is not null");
            return (Criteria) this;
        }

        public Criteria andBarCodeEqualTo(String value) {
            addCriterion("bar_code =", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotEqualTo(String value) {
            addCriterion("bar_code <>", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThan(String value) {
            addCriterion("bar_code >", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bar_code >=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThan(String value) {
            addCriterion("bar_code <", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLessThanOrEqualTo(String value) {
            addCriterion("bar_code <=", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeLike(String value) {
            addCriterion("bar_code like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotLike(String value) {
            addCriterion("bar_code not like", value, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeIn(List<String> values) {
            addCriterion("bar_code in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotIn(List<String> values) {
            addCriterion("bar_code not in", values, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeBetween(String value1, String value2) {
            addCriterion("bar_code between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andBarCodeNotBetween(String value1, String value2) {
            addCriterion("bar_code not between", value1, value2, "barCode");
            return (Criteria) this;
        }

        public Criteria andCateIdIsNull() {
            addCriterion("cate_id is null");
            return (Criteria) this;
        }

        public Criteria andCateIdIsNotNull() {
            addCriterion("cate_id is not null");
            return (Criteria) this;
        }

        public Criteria andCateIdEqualTo(String value) {
            addCriterion("cate_id =", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotEqualTo(String value) {
            addCriterion("cate_id <>", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdGreaterThan(String value) {
            addCriterion("cate_id >", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdGreaterThanOrEqualTo(String value) {
            addCriterion("cate_id >=", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdLessThan(String value) {
            addCriterion("cate_id <", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdLessThanOrEqualTo(String value) {
            addCriterion("cate_id <=", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdLike(String value) {
            addCriterion("cate_id like", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotLike(String value) {
            addCriterion("cate_id not like", value, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdIn(List<String> values) {
            addCriterion("cate_id in", values, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotIn(List<String> values) {
            addCriterion("cate_id not in", values, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdBetween(String value1, String value2) {
            addCriterion("cate_id between", value1, value2, "cateId");
            return (Criteria) this;
        }

        public Criteria andCateIdNotBetween(String value1, String value2) {
            addCriterion("cate_id not between", value1, value2, "cateId");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andVipPriceIsNull() {
            addCriterion("vip_price is null");
            return (Criteria) this;
        }

        public Criteria andVipPriceIsNotNull() {
            addCriterion("vip_price is not null");
            return (Criteria) this;
        }

        public Criteria andVipPriceEqualTo(BigDecimal value) {
            addCriterion("vip_price =", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceNotEqualTo(BigDecimal value) {
            addCriterion("vip_price <>", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceGreaterThan(BigDecimal value) {
            addCriterion("vip_price >", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("vip_price >=", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceLessThan(BigDecimal value) {
            addCriterion("vip_price <", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("vip_price <=", value, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceIn(List<BigDecimal> values) {
            addCriterion("vip_price in", values, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceNotIn(List<BigDecimal> values) {
            addCriterion("vip_price not in", values, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vip_price between", value1, value2, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andVipPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("vip_price not between", value1, value2, "vipPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceIsNull() {
            addCriterion("ot_price is null");
            return (Criteria) this;
        }

        public Criteria andOtPriceIsNotNull() {
            addCriterion("ot_price is not null");
            return (Criteria) this;
        }

        public Criteria andOtPriceEqualTo(BigDecimal value) {
            addCriterion("ot_price =", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceNotEqualTo(BigDecimal value) {
            addCriterion("ot_price <>", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceGreaterThan(BigDecimal value) {
            addCriterion("ot_price >", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ot_price >=", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceLessThan(BigDecimal value) {
            addCriterion("ot_price <", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ot_price <=", value, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceIn(List<BigDecimal> values) {
            addCriterion("ot_price in", values, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceNotIn(List<BigDecimal> values) {
            addCriterion("ot_price not in", values, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ot_price between", value1, value2, "otPrice");
            return (Criteria) this;
        }

        public Criteria andOtPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ot_price not between", value1, value2, "otPrice");
            return (Criteria) this;
        }

        public Criteria andPostageIsNull() {
            addCriterion("postage is null");
            return (Criteria) this;
        }

        public Criteria andPostageIsNotNull() {
            addCriterion("postage is not null");
            return (Criteria) this;
        }

        public Criteria andPostageEqualTo(BigDecimal value) {
            addCriterion("postage =", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageNotEqualTo(BigDecimal value) {
            addCriterion("postage <>", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageGreaterThan(BigDecimal value) {
            addCriterion("postage >", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("postage >=", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageLessThan(BigDecimal value) {
            addCriterion("postage <", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("postage <=", value, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageIn(List<BigDecimal> values) {
            addCriterion("postage in", values, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageNotIn(List<BigDecimal> values) {
            addCriterion("postage not in", values, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("postage between", value1, value2, "postage");
            return (Criteria) this;
        }

        public Criteria andPostageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("postage not between", value1, value2, "postage");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNull() {
            addCriterion("unit_name is null");
            return (Criteria) this;
        }

        public Criteria andUnitNameIsNotNull() {
            addCriterion("unit_name is not null");
            return (Criteria) this;
        }

        public Criteria andUnitNameEqualTo(String value) {
            addCriterion("unit_name =", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotEqualTo(String value) {
            addCriterion("unit_name <>", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThan(String value) {
            addCriterion("unit_name >", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameGreaterThanOrEqualTo(String value) {
            addCriterion("unit_name >=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThan(String value) {
            addCriterion("unit_name <", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLessThanOrEqualTo(String value) {
            addCriterion("unit_name <=", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameLike(String value) {
            addCriterion("unit_name like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotLike(String value) {
            addCriterion("unit_name not like", value, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameIn(List<String> values) {
            addCriterion("unit_name in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotIn(List<String> values) {
            addCriterion("unit_name not in", values, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameBetween(String value1, String value2) {
            addCriterion("unit_name between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andUnitNameNotBetween(String value1, String value2) {
            addCriterion("unit_name not between", value1, value2, "unitName");
            return (Criteria) this;
        }

        public Criteria andSortIsNull() {
            addCriterion("sort is null");
            return (Criteria) this;
        }

        public Criteria andSortIsNotNull() {
            addCriterion("sort is not null");
            return (Criteria) this;
        }

        public Criteria andSortEqualTo(Short value) {
            addCriterion("sort =", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotEqualTo(Short value) {
            addCriterion("sort <>", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThan(Short value) {
            addCriterion("sort >", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortGreaterThanOrEqualTo(Short value) {
            addCriterion("sort >=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThan(Short value) {
            addCriterion("sort <", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortLessThanOrEqualTo(Short value) {
            addCriterion("sort <=", value, "sort");
            return (Criteria) this;
        }

        public Criteria andSortIn(List<Short> values) {
            addCriterion("sort in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotIn(List<Short> values) {
            addCriterion("sort not in", values, "sort");
            return (Criteria) this;
        }

        public Criteria andSortBetween(Short value1, Short value2) {
            addCriterion("sort between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSortNotBetween(Short value1, Short value2) {
            addCriterion("sort not between", value1, value2, "sort");
            return (Criteria) this;
        }

        public Criteria andSalesIsNull() {
            addCriterion("sales is null");
            return (Criteria) this;
        }

        public Criteria andSalesIsNotNull() {
            addCriterion("sales is not null");
            return (Criteria) this;
        }

        public Criteria andSalesEqualTo(Integer value) {
            addCriterion("sales =", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesNotEqualTo(Integer value) {
            addCriterion("sales <>", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesGreaterThan(Integer value) {
            addCriterion("sales >", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("sales >=", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesLessThan(Integer value) {
            addCriterion("sales <", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesLessThanOrEqualTo(Integer value) {
            addCriterion("sales <=", value, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesIn(List<Integer> values) {
            addCriterion("sales in", values, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesNotIn(List<Integer> values) {
            addCriterion("sales not in", values, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesBetween(Integer value1, Integer value2) {
            addCriterion("sales between", value1, value2, "sales");
            return (Criteria) this;
        }

        public Criteria andSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("sales not between", value1, value2, "sales");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNull() {
            addCriterion("is_show is null");
            return (Criteria) this;
        }

        public Criteria andIsShowIsNotNull() {
            addCriterion("is_show is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowEqualTo(Boolean value) {
            addCriterion("is_show =", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotEqualTo(Boolean value) {
            addCriterion("is_show <>", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThan(Boolean value) {
            addCriterion("is_show >", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_show >=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThan(Boolean value) {
            addCriterion("is_show <", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowLessThanOrEqualTo(Boolean value) {
            addCriterion("is_show <=", value, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowIn(List<Boolean> values) {
            addCriterion("is_show in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotIn(List<Boolean> values) {
            addCriterion("is_show not in", values, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsShowNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_show not between", value1, value2, "isShow");
            return (Criteria) this;
        }

        public Criteria andIsHotIsNull() {
            addCriterion("is_hot is null");
            return (Criteria) this;
        }

        public Criteria andIsHotIsNotNull() {
            addCriterion("is_hot is not null");
            return (Criteria) this;
        }

        public Criteria andIsHotEqualTo(Boolean value) {
            addCriterion("is_hot =", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotEqualTo(Boolean value) {
            addCriterion("is_hot <>", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotGreaterThan(Boolean value) {
            addCriterion("is_hot >", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_hot >=", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotLessThan(Boolean value) {
            addCriterion("is_hot <", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotLessThanOrEqualTo(Boolean value) {
            addCriterion("is_hot <=", value, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotIn(List<Boolean> values) {
            addCriterion("is_hot in", values, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotIn(List<Boolean> values) {
            addCriterion("is_hot not in", values, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_hot between", value1, value2, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsHotNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_hot not between", value1, value2, "isHot");
            return (Criteria) this;
        }

        public Criteria andIsBenefitIsNull() {
            addCriterion("is_benefit is null");
            return (Criteria) this;
        }

        public Criteria andIsBenefitIsNotNull() {
            addCriterion("is_benefit is not null");
            return (Criteria) this;
        }

        public Criteria andIsBenefitEqualTo(Boolean value) {
            addCriterion("is_benefit =", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitNotEqualTo(Boolean value) {
            addCriterion("is_benefit <>", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitGreaterThan(Boolean value) {
            addCriterion("is_benefit >", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_benefit >=", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitLessThan(Boolean value) {
            addCriterion("is_benefit <", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitLessThanOrEqualTo(Boolean value) {
            addCriterion("is_benefit <=", value, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitIn(List<Boolean> values) {
            addCriterion("is_benefit in", values, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitNotIn(List<Boolean> values) {
            addCriterion("is_benefit not in", values, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitBetween(Boolean value1, Boolean value2) {
            addCriterion("is_benefit between", value1, value2, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBenefitNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_benefit not between", value1, value2, "isBenefit");
            return (Criteria) this;
        }

        public Criteria andIsBestIsNull() {
            addCriterion("is_best is null");
            return (Criteria) this;
        }

        public Criteria andIsBestIsNotNull() {
            addCriterion("is_best is not null");
            return (Criteria) this;
        }

        public Criteria andIsBestEqualTo(Boolean value) {
            addCriterion("is_best =", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestNotEqualTo(Boolean value) {
            addCriterion("is_best <>", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestGreaterThan(Boolean value) {
            addCriterion("is_best >", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_best >=", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestLessThan(Boolean value) {
            addCriterion("is_best <", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestLessThanOrEqualTo(Boolean value) {
            addCriterion("is_best <=", value, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestIn(List<Boolean> values) {
            addCriterion("is_best in", values, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestNotIn(List<Boolean> values) {
            addCriterion("is_best not in", values, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestBetween(Boolean value1, Boolean value2) {
            addCriterion("is_best between", value1, value2, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsBestNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_best not between", value1, value2, "isBest");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNull() {
            addCriterion("is_new is null");
            return (Criteria) this;
        }

        public Criteria andIsNewIsNotNull() {
            addCriterion("is_new is not null");
            return (Criteria) this;
        }

        public Criteria andIsNewEqualTo(Boolean value) {
            addCriterion("is_new =", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotEqualTo(Boolean value) {
            addCriterion("is_new <>", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThan(Boolean value) {
            addCriterion("is_new >", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_new >=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThan(Boolean value) {
            addCriterion("is_new <", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewLessThanOrEqualTo(Boolean value) {
            addCriterion("is_new <=", value, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewIn(List<Boolean> values) {
            addCriterion("is_new in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotIn(List<Boolean> values) {
            addCriterion("is_new not in", values, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewBetween(Boolean value1, Boolean value2) {
            addCriterion("is_new between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andIsNewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_new not between", value1, value2, "isNew");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNull() {
            addCriterion("add_time is null");
            return (Criteria) this;
        }

        public Criteria andAddTimeIsNotNull() {
            addCriterion("add_time is not null");
            return (Criteria) this;
        }

        public Criteria andAddTimeEqualTo(Integer value) {
            addCriterion("add_time =", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotEqualTo(Integer value) {
            addCriterion("add_time <>", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThan(Integer value) {
            addCriterion("add_time >", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("add_time >=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThan(Integer value) {
            addCriterion("add_time <", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeLessThanOrEqualTo(Integer value) {
            addCriterion("add_time <=", value, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeIn(List<Integer> values) {
            addCriterion("add_time in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotIn(List<Integer> values) {
            addCriterion("add_time not in", values, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeBetween(Integer value1, Integer value2) {
            addCriterion("add_time between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andAddTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("add_time not between", value1, value2, "addTime");
            return (Criteria) this;
        }

        public Criteria andIsPostageIsNull() {
            addCriterion("is_postage is null");
            return (Criteria) this;
        }

        public Criteria andIsPostageIsNotNull() {
            addCriterion("is_postage is not null");
            return (Criteria) this;
        }

        public Criteria andIsPostageEqualTo(Boolean value) {
            addCriterion("is_postage =", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageNotEqualTo(Boolean value) {
            addCriterion("is_postage <>", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageGreaterThan(Boolean value) {
            addCriterion("is_postage >", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_postage >=", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageLessThan(Boolean value) {
            addCriterion("is_postage <", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageLessThanOrEqualTo(Boolean value) {
            addCriterion("is_postage <=", value, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageIn(List<Boolean> values) {
            addCriterion("is_postage in", values, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageNotIn(List<Boolean> values) {
            addCriterion("is_postage not in", values, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageBetween(Boolean value1, Boolean value2) {
            addCriterion("is_postage between", value1, value2, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsPostageNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_postage not between", value1, value2, "isPostage");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(Boolean value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(Boolean value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(Boolean value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(Boolean value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(Boolean value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<Boolean> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<Boolean> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andMerUseIsNull() {
            addCriterion("mer_use is null");
            return (Criteria) this;
        }

        public Criteria andMerUseIsNotNull() {
            addCriterion("mer_use is not null");
            return (Criteria) this;
        }

        public Criteria andMerUseEqualTo(Boolean value) {
            addCriterion("mer_use =", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseNotEqualTo(Boolean value) {
            addCriterion("mer_use <>", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseGreaterThan(Boolean value) {
            addCriterion("mer_use >", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseGreaterThanOrEqualTo(Boolean value) {
            addCriterion("mer_use >=", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseLessThan(Boolean value) {
            addCriterion("mer_use <", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseLessThanOrEqualTo(Boolean value) {
            addCriterion("mer_use <=", value, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseIn(List<Boolean> values) {
            addCriterion("mer_use in", values, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseNotIn(List<Boolean> values) {
            addCriterion("mer_use not in", values, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseBetween(Boolean value1, Boolean value2) {
            addCriterion("mer_use between", value1, value2, "merUse");
            return (Criteria) this;
        }

        public Criteria andMerUseNotBetween(Boolean value1, Boolean value2) {
            addCriterion("mer_use not between", value1, value2, "merUse");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralIsNull() {
            addCriterion("give_integral is null");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralIsNotNull() {
            addCriterion("give_integral is not null");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralEqualTo(Integer value) {
            addCriterion("give_integral =", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralNotEqualTo(Integer value) {
            addCriterion("give_integral <>", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralGreaterThan(Integer value) {
            addCriterion("give_integral >", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralGreaterThanOrEqualTo(Integer value) {
            addCriterion("give_integral >=", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralLessThan(Integer value) {
            addCriterion("give_integral <", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralLessThanOrEqualTo(Integer value) {
            addCriterion("give_integral <=", value, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralIn(List<Integer> values) {
            addCriterion("give_integral in", values, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralNotIn(List<Integer> values) {
            addCriterion("give_integral not in", values, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralBetween(Integer value1, Integer value2) {
            addCriterion("give_integral between", value1, value2, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andGiveIntegralNotBetween(Integer value1, Integer value2) {
            addCriterion("give_integral not between", value1, value2, "giveIntegral");
            return (Criteria) this;
        }

        public Criteria andCostIsNull() {
            addCriterion("cost is null");
            return (Criteria) this;
        }

        public Criteria andCostIsNotNull() {
            addCriterion("cost is not null");
            return (Criteria) this;
        }

        public Criteria andCostEqualTo(BigDecimal value) {
            addCriterion("cost =", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotEqualTo(BigDecimal value) {
            addCriterion("cost <>", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThan(BigDecimal value) {
            addCriterion("cost >", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost >=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThan(BigDecimal value) {
            addCriterion("cost <", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost <=", value, "cost");
            return (Criteria) this;
        }

        public Criteria andCostIn(List<BigDecimal> values) {
            addCriterion("cost in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotIn(List<BigDecimal> values) {
            addCriterion("cost not in", values, "cost");
            return (Criteria) this;
        }

        public Criteria andCostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andCostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost not between", value1, value2, "cost");
            return (Criteria) this;
        }

        public Criteria andIsSeckillIsNull() {
            addCriterion("is_seckill is null");
            return (Criteria) this;
        }

        public Criteria andIsSeckillIsNotNull() {
            addCriterion("is_seckill is not null");
            return (Criteria) this;
        }

        public Criteria andIsSeckillEqualTo(Boolean value) {
            addCriterion("is_seckill =", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillNotEqualTo(Boolean value) {
            addCriterion("is_seckill <>", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillGreaterThan(Boolean value) {
            addCriterion("is_seckill >", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_seckill >=", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillLessThan(Boolean value) {
            addCriterion("is_seckill <", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillLessThanOrEqualTo(Boolean value) {
            addCriterion("is_seckill <=", value, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillIn(List<Boolean> values) {
            addCriterion("is_seckill in", values, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillNotIn(List<Boolean> values) {
            addCriterion("is_seckill not in", values, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillBetween(Boolean value1, Boolean value2) {
            addCriterion("is_seckill between", value1, value2, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsSeckillNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_seckill not between", value1, value2, "isSeckill");
            return (Criteria) this;
        }

        public Criteria andIsBargainIsNull() {
            addCriterion("is_bargain is null");
            return (Criteria) this;
        }

        public Criteria andIsBargainIsNotNull() {
            addCriterion("is_bargain is not null");
            return (Criteria) this;
        }

        public Criteria andIsBargainEqualTo(Boolean value) {
            addCriterion("is_bargain =", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainNotEqualTo(Boolean value) {
            addCriterion("is_bargain <>", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainGreaterThan(Boolean value) {
            addCriterion("is_bargain >", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_bargain >=", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainLessThan(Boolean value) {
            addCriterion("is_bargain <", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainLessThanOrEqualTo(Boolean value) {
            addCriterion("is_bargain <=", value, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainIn(List<Boolean> values) {
            addCriterion("is_bargain in", values, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainNotIn(List<Boolean> values) {
            addCriterion("is_bargain not in", values, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bargain between", value1, value2, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsBargainNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bargain not between", value1, value2, "isBargain");
            return (Criteria) this;
        }

        public Criteria andIsGoodIsNull() {
            addCriterion("is_good is null");
            return (Criteria) this;
        }

        public Criteria andIsGoodIsNotNull() {
            addCriterion("is_good is not null");
            return (Criteria) this;
        }

        public Criteria andIsGoodEqualTo(Boolean value) {
            addCriterion("is_good =", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodNotEqualTo(Boolean value) {
            addCriterion("is_good <>", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodGreaterThan(Boolean value) {
            addCriterion("is_good >", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_good >=", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodLessThan(Boolean value) {
            addCriterion("is_good <", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodLessThanOrEqualTo(Boolean value) {
            addCriterion("is_good <=", value, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodIn(List<Boolean> values) {
            addCriterion("is_good in", values, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodNotIn(List<Boolean> values) {
            addCriterion("is_good not in", values, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodBetween(Boolean value1, Boolean value2) {
            addCriterion("is_good between", value1, value2, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsGoodNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_good not between", value1, value2, "isGood");
            return (Criteria) this;
        }

        public Criteria andIsSubIsNull() {
            addCriterion("is_sub is null");
            return (Criteria) this;
        }

        public Criteria andIsSubIsNotNull() {
            addCriterion("is_sub is not null");
            return (Criteria) this;
        }

        public Criteria andIsSubEqualTo(Boolean value) {
            addCriterion("is_sub =", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubNotEqualTo(Boolean value) {
            addCriterion("is_sub <>", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubGreaterThan(Boolean value) {
            addCriterion("is_sub >", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_sub >=", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubLessThan(Boolean value) {
            addCriterion("is_sub <", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubLessThanOrEqualTo(Boolean value) {
            addCriterion("is_sub <=", value, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubIn(List<Boolean> values) {
            addCriterion("is_sub in", values, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubNotIn(List<Boolean> values) {
            addCriterion("is_sub not in", values, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sub between", value1, value2, "isSub");
            return (Criteria) this;
        }

        public Criteria andIsSubNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_sub not between", value1, value2, "isSub");
            return (Criteria) this;
        }

        public Criteria andFictiIsNull() {
            addCriterion("ficti is null");
            return (Criteria) this;
        }

        public Criteria andFictiIsNotNull() {
            addCriterion("ficti is not null");
            return (Criteria) this;
        }

        public Criteria andFictiEqualTo(Integer value) {
            addCriterion("ficti =", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiNotEqualTo(Integer value) {
            addCriterion("ficti <>", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiGreaterThan(Integer value) {
            addCriterion("ficti >", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiGreaterThanOrEqualTo(Integer value) {
            addCriterion("ficti >=", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiLessThan(Integer value) {
            addCriterion("ficti <", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiLessThanOrEqualTo(Integer value) {
            addCriterion("ficti <=", value, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiIn(List<Integer> values) {
            addCriterion("ficti in", values, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiNotIn(List<Integer> values) {
            addCriterion("ficti not in", values, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiBetween(Integer value1, Integer value2) {
            addCriterion("ficti between", value1, value2, "ficti");
            return (Criteria) this;
        }

        public Criteria andFictiNotBetween(Integer value1, Integer value2) {
            addCriterion("ficti not between", value1, value2, "ficti");
            return (Criteria) this;
        }

        public Criteria andBrowseIsNull() {
            addCriterion("browse is null");
            return (Criteria) this;
        }

        public Criteria andBrowseIsNotNull() {
            addCriterion("browse is not null");
            return (Criteria) this;
        }

        public Criteria andBrowseEqualTo(Integer value) {
            addCriterion("browse =", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseNotEqualTo(Integer value) {
            addCriterion("browse <>", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseGreaterThan(Integer value) {
            addCriterion("browse >", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseGreaterThanOrEqualTo(Integer value) {
            addCriterion("browse >=", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseLessThan(Integer value) {
            addCriterion("browse <", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseLessThanOrEqualTo(Integer value) {
            addCriterion("browse <=", value, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseIn(List<Integer> values) {
            addCriterion("browse in", values, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseNotIn(List<Integer> values) {
            addCriterion("browse not in", values, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseBetween(Integer value1, Integer value2) {
            addCriterion("browse between", value1, value2, "browse");
            return (Criteria) this;
        }

        public Criteria andBrowseNotBetween(Integer value1, Integer value2) {
            addCriterion("browse not between", value1, value2, "browse");
            return (Criteria) this;
        }

        public Criteria andCodePathIsNull() {
            addCriterion("code_path is null");
            return (Criteria) this;
        }

        public Criteria andCodePathIsNotNull() {
            addCriterion("code_path is not null");
            return (Criteria) this;
        }

        public Criteria andCodePathEqualTo(String value) {
            addCriterion("code_path =", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotEqualTo(String value) {
            addCriterion("code_path <>", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathGreaterThan(String value) {
            addCriterion("code_path >", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathGreaterThanOrEqualTo(String value) {
            addCriterion("code_path >=", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLessThan(String value) {
            addCriterion("code_path <", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLessThanOrEqualTo(String value) {
            addCriterion("code_path <=", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathLike(String value) {
            addCriterion("code_path like", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotLike(String value) {
            addCriterion("code_path not like", value, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathIn(List<String> values) {
            addCriterion("code_path in", values, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotIn(List<String> values) {
            addCriterion("code_path not in", values, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathBetween(String value1, String value2) {
            addCriterion("code_path between", value1, value2, "codePath");
            return (Criteria) this;
        }

        public Criteria andCodePathNotBetween(String value1, String value2) {
            addCriterion("code_path not between", value1, value2, "codePath");
            return (Criteria) this;
        }

        public Criteria andSoureLinkIsNull() {
            addCriterion("soure_link is null");
            return (Criteria) this;
        }

        public Criteria andSoureLinkIsNotNull() {
            addCriterion("soure_link is not null");
            return (Criteria) this;
        }

        public Criteria andSoureLinkEqualTo(String value) {
            addCriterion("soure_link =", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkNotEqualTo(String value) {
            addCriterion("soure_link <>", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkGreaterThan(String value) {
            addCriterion("soure_link >", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkGreaterThanOrEqualTo(String value) {
            addCriterion("soure_link >=", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkLessThan(String value) {
            addCriterion("soure_link <", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkLessThanOrEqualTo(String value) {
            addCriterion("soure_link <=", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkLike(String value) {
            addCriterion("soure_link like", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkNotLike(String value) {
            addCriterion("soure_link not like", value, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkIn(List<String> values) {
            addCriterion("soure_link in", values, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkNotIn(List<String> values) {
            addCriterion("soure_link not in", values, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkBetween(String value1, String value2) {
            addCriterion("soure_link between", value1, value2, "soureLink");
            return (Criteria) this;
        }

        public Criteria andSoureLinkNotBetween(String value1, String value2) {
            addCriterion("soure_link not between", value1, value2, "soureLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIsNull() {
            addCriterion("video_link is null");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIsNotNull() {
            addCriterion("video_link is not null");
            return (Criteria) this;
        }

        public Criteria andVideoLinkEqualTo(String value) {
            addCriterion("video_link =", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotEqualTo(String value) {
            addCriterion("video_link <>", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkGreaterThan(String value) {
            addCriterion("video_link >", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkGreaterThanOrEqualTo(String value) {
            addCriterion("video_link >=", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLessThan(String value) {
            addCriterion("video_link <", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLessThanOrEqualTo(String value) {
            addCriterion("video_link <=", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkLike(String value) {
            addCriterion("video_link like", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotLike(String value) {
            addCriterion("video_link not like", value, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkIn(List<String> values) {
            addCriterion("video_link in", values, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotIn(List<String> values) {
            addCriterion("video_link not in", values, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkBetween(String value1, String value2) {
            addCriterion("video_link between", value1, value2, "videoLink");
            return (Criteria) this;
        }

        public Criteria andVideoLinkNotBetween(String value1, String value2) {
            addCriterion("video_link not between", value1, value2, "videoLink");
            return (Criteria) this;
        }

        public Criteria andTempIdIsNull() {
            addCriterion("temp_id is null");
            return (Criteria) this;
        }

        public Criteria andTempIdIsNotNull() {
            addCriterion("temp_id is not null");
            return (Criteria) this;
        }

        public Criteria andTempIdEqualTo(Integer value) {
            addCriterion("temp_id =", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotEqualTo(Integer value) {
            addCriterion("temp_id <>", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThan(Integer value) {
            addCriterion("temp_id >", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("temp_id >=", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThan(Integer value) {
            addCriterion("temp_id <", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdLessThanOrEqualTo(Integer value) {
            addCriterion("temp_id <=", value, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdIn(List<Integer> values) {
            addCriterion("temp_id in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotIn(List<Integer> values) {
            addCriterion("temp_id not in", values, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdBetween(Integer value1, Integer value2) {
            addCriterion("temp_id between", value1, value2, "tempId");
            return (Criteria) this;
        }

        public Criteria andTempIdNotBetween(Integer value1, Integer value2) {
            addCriterion("temp_id not between", value1, value2, "tempId");
            return (Criteria) this;
        }

        public Criteria andSpecTypeIsNull() {
            addCriterion("spec_type is null");
            return (Criteria) this;
        }

        public Criteria andSpecTypeIsNotNull() {
            addCriterion("spec_type is not null");
            return (Criteria) this;
        }

        public Criteria andSpecTypeEqualTo(Boolean value) {
            addCriterion("spec_type =", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeNotEqualTo(Boolean value) {
            addCriterion("spec_type <>", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeGreaterThan(Boolean value) {
            addCriterion("spec_type >", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeGreaterThanOrEqualTo(Boolean value) {
            addCriterion("spec_type >=", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeLessThan(Boolean value) {
            addCriterion("spec_type <", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeLessThanOrEqualTo(Boolean value) {
            addCriterion("spec_type <=", value, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeIn(List<Boolean> values) {
            addCriterion("spec_type in", values, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeNotIn(List<Boolean> values) {
            addCriterion("spec_type not in", values, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeBetween(Boolean value1, Boolean value2) {
            addCriterion("spec_type between", value1, value2, "specType");
            return (Criteria) this;
        }

        public Criteria andSpecTypeNotBetween(Boolean value1, Boolean value2) {
            addCriterion("spec_type not between", value1, value2, "specType");
            return (Criteria) this;
        }

        public Criteria andActivityIsNull() {
            addCriterion("activity is null");
            return (Criteria) this;
        }

        public Criteria andActivityIsNotNull() {
            addCriterion("activity is not null");
            return (Criteria) this;
        }

        public Criteria andActivityEqualTo(String value) {
            addCriterion("activity =", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotEqualTo(String value) {
            addCriterion("activity <>", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThan(String value) {
            addCriterion("activity >", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityGreaterThanOrEqualTo(String value) {
            addCriterion("activity >=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThan(String value) {
            addCriterion("activity <", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLessThanOrEqualTo(String value) {
            addCriterion("activity <=", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityLike(String value) {
            addCriterion("activity like", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotLike(String value) {
            addCriterion("activity not like", value, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityIn(List<String> values) {
            addCriterion("activity in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotIn(List<String> values) {
            addCriterion("activity not in", values, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityBetween(String value1, String value2) {
            addCriterion("activity between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andActivityNotBetween(String value1, String value2) {
            addCriterion("activity not between", value1, value2, "activity");
            return (Criteria) this;
        }

        public Criteria andFlatPatternIsNull() {
            addCriterion("flat_pattern is null");
            return (Criteria) this;
        }

        public Criteria andFlatPatternIsNotNull() {
            addCriterion("flat_pattern is not null");
            return (Criteria) this;
        }

        public Criteria andFlatPatternEqualTo(String value) {
            addCriterion("flat_pattern =", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternNotEqualTo(String value) {
            addCriterion("flat_pattern <>", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternGreaterThan(String value) {
            addCriterion("flat_pattern >", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternGreaterThanOrEqualTo(String value) {
            addCriterion("flat_pattern >=", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternLessThan(String value) {
            addCriterion("flat_pattern <", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternLessThanOrEqualTo(String value) {
            addCriterion("flat_pattern <=", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternLike(String value) {
            addCriterion("flat_pattern like", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternNotLike(String value) {
            addCriterion("flat_pattern not like", value, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternIn(List<String> values) {
            addCriterion("flat_pattern in", values, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternNotIn(List<String> values) {
            addCriterion("flat_pattern not in", values, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternBetween(String value1, String value2) {
            addCriterion("flat_pattern between", value1, value2, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andFlatPatternNotBetween(String value1, String value2) {
            addCriterion("flat_pattern not between", value1, value2, "flatPattern");
            return (Criteria) this;
        }

        public Criteria andIsRecycleIsNull() {
            addCriterion("is_recycle is null");
            return (Criteria) this;
        }

        public Criteria andIsRecycleIsNotNull() {
            addCriterion("is_recycle is not null");
            return (Criteria) this;
        }

        public Criteria andIsRecycleEqualTo(Boolean value) {
            addCriterion("is_recycle =", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleNotEqualTo(Boolean value) {
            addCriterion("is_recycle <>", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleGreaterThan(Boolean value) {
            addCriterion("is_recycle >", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_recycle >=", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleLessThan(Boolean value) {
            addCriterion("is_recycle <", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleLessThanOrEqualTo(Boolean value) {
            addCriterion("is_recycle <=", value, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleIn(List<Boolean> values) {
            addCriterion("is_recycle in", values, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleNotIn(List<Boolean> values) {
            addCriterion("is_recycle not in", values, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleBetween(Boolean value1, Boolean value2) {
            addCriterion("is_recycle between", value1, value2, "isRecycle");
            return (Criteria) this;
        }

        public Criteria andIsRecycleNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_recycle not between", value1, value2, "isRecycle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eb_store_product
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}