package mall.pojo;

import java.math.BigDecimal;

public class EbStoreProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.mer_id
     *
     * @mbg.generated
     */
    private Integer merId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.image
     *
     * @mbg.generated
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.slider_image
     *
     * @mbg.generated
     */
    private String sliderImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.store_name
     *
     * @mbg.generated
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.store_info
     *
     * @mbg.generated
     */
    private String storeInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.keyword
     *
     * @mbg.generated
     */
    private String keyword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.bar_code
     *
     * @mbg.generated
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.cate_id
     *
     * @mbg.generated
     */
    private String cateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.vip_price
     *
     * @mbg.generated
     */
    private BigDecimal vipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ot_price
     *
     * @mbg.generated
     */
    private BigDecimal otPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.postage
     *
     * @mbg.generated
     */
    private BigDecimal postage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.unit_name
     *
     * @mbg.generated
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sort
     *
     * @mbg.generated
     */
    private Short sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.sales
     *
     * @mbg.generated
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.stock
     *
     * @mbg.generated
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_show
     *
     * @mbg.generated
     */
    private Boolean isShow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_hot
     *
     * @mbg.generated
     */
    private Boolean isHot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    private Boolean isBenefit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_best
     *
     * @mbg.generated
     */
    private Boolean isBest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_new
     *
     * @mbg.generated
     */
    private Boolean isNew;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.add_time
     *
     * @mbg.generated
     */
    private Integer addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_postage
     *
     * @mbg.generated
     */
    private Boolean isPostage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.mer_use
     *
     * @mbg.generated
     */
    private Boolean merUse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.give_integral
     *
     * @mbg.generated
     */
    private Integer giveIntegral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.cost
     *
     * @mbg.generated
     */
    private BigDecimal cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    private Boolean isSeckill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    private Boolean isBargain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_good
     *
     * @mbg.generated
     */
    private Boolean isGood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_sub
     *
     * @mbg.generated
     */
    private Boolean isSub;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.ficti
     *
     * @mbg.generated
     */
    private Integer ficti;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.browse
     *
     * @mbg.generated
     */
    private Integer browse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.code_path
     *
     * @mbg.generated
     */
    private String codePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.soure_link
     *
     * @mbg.generated
     */
    private String soureLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.video_link
     *
     * @mbg.generated
     */
    private String videoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.temp_id
     *
     * @mbg.generated
     */
    private Integer tempId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.spec_type
     *
     * @mbg.generated
     */
    private Boolean specType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.activity
     *
     * @mbg.generated
     */
    private String activity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.flat_pattern
     *
     * @mbg.generated
     */
    private String flatPattern;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_store_product.is_recycle
     *
     * @mbg.generated
     */
    private Boolean isRecycle;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public EbStoreProduct(Integer id, Integer merId, String image, String sliderImage, String storeName, String storeInfo, String keyword, String barCode, String cateId, BigDecimal price, BigDecimal vipPrice, BigDecimal otPrice, BigDecimal postage, String unitName, Short sort, Integer sales, Integer stock, Boolean isShow, Boolean isHot, Boolean isBenefit, Boolean isBest, Boolean isNew, Integer addTime, Boolean isPostage, Boolean isDel, Boolean merUse, Integer giveIntegral, BigDecimal cost, Boolean isSeckill, Boolean isBargain, Boolean isGood, Boolean isSub, Integer ficti, Integer browse, String codePath, String soureLink, String videoLink, Integer tempId, Boolean specType, String activity, String flatPattern, Boolean isRecycle) {
        this.id = id;
        this.merId = merId;
        this.image = image;
        this.sliderImage = sliderImage;
        this.storeName = storeName;
        this.storeInfo = storeInfo;
        this.keyword = keyword;
        this.barCode = barCode;
        this.cateId = cateId;
        this.price = price;
        this.vipPrice = vipPrice;
        this.otPrice = otPrice;
        this.postage = postage;
        this.unitName = unitName;
        this.sort = sort;
        this.sales = sales;
        this.stock = stock;
        this.isShow = isShow;
        this.isHot = isHot;
        this.isBenefit = isBenefit;
        this.isBest = isBest;
        this.isNew = isNew;
        this.addTime = addTime;
        this.isPostage = isPostage;
        this.isDel = isDel;
        this.merUse = merUse;
        this.giveIntegral = giveIntegral;
        this.cost = cost;
        this.isSeckill = isSeckill;
        this.isBargain = isBargain;
        this.isGood = isGood;
        this.isSub = isSub;
        this.ficti = ficti;
        this.browse = browse;
        this.codePath = codePath;
        this.soureLink = soureLink;
        this.videoLink = videoLink;
        this.tempId = tempId;
        this.specType = specType;
        this.activity = activity;
        this.flatPattern = flatPattern;
        this.isRecycle = isRecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    public EbStoreProduct() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.id
     *
     * @return the value of eb_store_product.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.id
     *
     * @param id the value for eb_store_product.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.mer_id
     *
     * @return the value of eb_store_product.mer_id
     *
     * @mbg.generated
     */
    public Integer getMerId() {
        return merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.mer_id
     *
     * @param merId the value for eb_store_product.mer_id
     *
     * @mbg.generated
     */
    public void setMerId(Integer merId) {
        this.merId = merId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.image
     *
     * @return the value of eb_store_product.image
     *
     * @mbg.generated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.image
     *
     * @param image the value for eb_store_product.image
     *
     * @mbg.generated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.slider_image
     *
     * @return the value of eb_store_product.slider_image
     *
     * @mbg.generated
     */
    public String getSliderImage() {
        return sliderImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.slider_image
     *
     * @param sliderImage the value for eb_store_product.slider_image
     *
     * @mbg.generated
     */
    public void setSliderImage(String sliderImage) {
        this.sliderImage = sliderImage == null ? null : sliderImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.store_name
     *
     * @return the value of eb_store_product.store_name
     *
     * @mbg.generated
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.store_name
     *
     * @param storeName the value for eb_store_product.store_name
     *
     * @mbg.generated
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.store_info
     *
     * @return the value of eb_store_product.store_info
     *
     * @mbg.generated
     */
    public String getStoreInfo() {
        return storeInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.store_info
     *
     * @param storeInfo the value for eb_store_product.store_info
     *
     * @mbg.generated
     */
    public void setStoreInfo(String storeInfo) {
        this.storeInfo = storeInfo == null ? null : storeInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.keyword
     *
     * @return the value of eb_store_product.keyword
     *
     * @mbg.generated
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.keyword
     *
     * @param keyword the value for eb_store_product.keyword
     *
     * @mbg.generated
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.bar_code
     *
     * @return the value of eb_store_product.bar_code
     *
     * @mbg.generated
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.bar_code
     *
     * @param barCode the value for eb_store_product.bar_code
     *
     * @mbg.generated
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.cate_id
     *
     * @return the value of eb_store_product.cate_id
     *
     * @mbg.generated
     */
    public String getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.cate_id
     *
     * @param cateId the value for eb_store_product.cate_id
     *
     * @mbg.generated
     */
    public void setCateId(String cateId) {
        this.cateId = cateId == null ? null : cateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.price
     *
     * @return the value of eb_store_product.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.price
     *
     * @param price the value for eb_store_product.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.vip_price
     *
     * @return the value of eb_store_product.vip_price
     *
     * @mbg.generated
     */
    public BigDecimal getVipPrice() {
        return vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.vip_price
     *
     * @param vipPrice the value for eb_store_product.vip_price
     *
     * @mbg.generated
     */
    public void setVipPrice(BigDecimal vipPrice) {
        this.vipPrice = vipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ot_price
     *
     * @return the value of eb_store_product.ot_price
     *
     * @mbg.generated
     */
    public BigDecimal getOtPrice() {
        return otPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ot_price
     *
     * @param otPrice the value for eb_store_product.ot_price
     *
     * @mbg.generated
     */
    public void setOtPrice(BigDecimal otPrice) {
        this.otPrice = otPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.postage
     *
     * @return the value of eb_store_product.postage
     *
     * @mbg.generated
     */
    public BigDecimal getPostage() {
        return postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.postage
     *
     * @param postage the value for eb_store_product.postage
     *
     * @mbg.generated
     */
    public void setPostage(BigDecimal postage) {
        this.postage = postage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.unit_name
     *
     * @return the value of eb_store_product.unit_name
     *
     * @mbg.generated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.unit_name
     *
     * @param unitName the value for eb_store_product.unit_name
     *
     * @mbg.generated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sort
     *
     * @return the value of eb_store_product.sort
     *
     * @mbg.generated
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sort
     *
     * @param sort the value for eb_store_product.sort
     *
     * @mbg.generated
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.sales
     *
     * @return the value of eb_store_product.sales
     *
     * @mbg.generated
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.sales
     *
     * @param sales the value for eb_store_product.sales
     *
     * @mbg.generated
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.stock
     *
     * @return the value of eb_store_product.stock
     *
     * @mbg.generated
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.stock
     *
     * @param stock the value for eb_store_product.stock
     *
     * @mbg.generated
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_show
     *
     * @return the value of eb_store_product.is_show
     *
     * @mbg.generated
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_show
     *
     * @param isShow the value for eb_store_product.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_hot
     *
     * @return the value of eb_store_product.is_hot
     *
     * @mbg.generated
     */
    public Boolean getIsHot() {
        return isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_hot
     *
     * @param isHot the value for eb_store_product.is_hot
     *
     * @mbg.generated
     */
    public void setIsHot(Boolean isHot) {
        this.isHot = isHot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_benefit
     *
     * @return the value of eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    public Boolean getIsBenefit() {
        return isBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_benefit
     *
     * @param isBenefit the value for eb_store_product.is_benefit
     *
     * @mbg.generated
     */
    public void setIsBenefit(Boolean isBenefit) {
        this.isBenefit = isBenefit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_best
     *
     * @return the value of eb_store_product.is_best
     *
     * @mbg.generated
     */
    public Boolean getIsBest() {
        return isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_best
     *
     * @param isBest the value for eb_store_product.is_best
     *
     * @mbg.generated
     */
    public void setIsBest(Boolean isBest) {
        this.isBest = isBest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_new
     *
     * @return the value of eb_store_product.is_new
     *
     * @mbg.generated
     */
    public Boolean getIsNew() {
        return isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_new
     *
     * @param isNew the value for eb_store_product.is_new
     *
     * @mbg.generated
     */
    public void setIsNew(Boolean isNew) {
        this.isNew = isNew;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.add_time
     *
     * @return the value of eb_store_product.add_time
     *
     * @mbg.generated
     */
    public Integer getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.add_time
     *
     * @param addTime the value for eb_store_product.add_time
     *
     * @mbg.generated
     */
    public void setAddTime(Integer addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_postage
     *
     * @return the value of eb_store_product.is_postage
     *
     * @mbg.generated
     */
    public Boolean getIsPostage() {
        return isPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_postage
     *
     * @param isPostage the value for eb_store_product.is_postage
     *
     * @mbg.generated
     */
    public void setIsPostage(Boolean isPostage) {
        this.isPostage = isPostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_del
     *
     * @return the value of eb_store_product.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_del
     *
     * @param isDel the value for eb_store_product.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.mer_use
     *
     * @return the value of eb_store_product.mer_use
     *
     * @mbg.generated
     */
    public Boolean getMerUse() {
        return merUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.mer_use
     *
     * @param merUse the value for eb_store_product.mer_use
     *
     * @mbg.generated
     */
    public void setMerUse(Boolean merUse) {
        this.merUse = merUse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.give_integral
     *
     * @return the value of eb_store_product.give_integral
     *
     * @mbg.generated
     */
    public Integer getGiveIntegral() {
        return giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.give_integral
     *
     * @param giveIntegral the value for eb_store_product.give_integral
     *
     * @mbg.generated
     */
    public void setGiveIntegral(Integer giveIntegral) {
        this.giveIntegral = giveIntegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.cost
     *
     * @return the value of eb_store_product.cost
     *
     * @mbg.generated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.cost
     *
     * @param cost the value for eb_store_product.cost
     *
     * @mbg.generated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_seckill
     *
     * @return the value of eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    public Boolean getIsSeckill() {
        return isSeckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_seckill
     *
     * @param isSeckill the value for eb_store_product.is_seckill
     *
     * @mbg.generated
     */
    public void setIsSeckill(Boolean isSeckill) {
        this.isSeckill = isSeckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_bargain
     *
     * @return the value of eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    public Boolean getIsBargain() {
        return isBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_bargain
     *
     * @param isBargain the value for eb_store_product.is_bargain
     *
     * @mbg.generated
     */
    public void setIsBargain(Boolean isBargain) {
        this.isBargain = isBargain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_good
     *
     * @return the value of eb_store_product.is_good
     *
     * @mbg.generated
     */
    public Boolean getIsGood() {
        return isGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_good
     *
     * @param isGood the value for eb_store_product.is_good
     *
     * @mbg.generated
     */
    public void setIsGood(Boolean isGood) {
        this.isGood = isGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_sub
     *
     * @return the value of eb_store_product.is_sub
     *
     * @mbg.generated
     */
    public Boolean getIsSub() {
        return isSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_sub
     *
     * @param isSub the value for eb_store_product.is_sub
     *
     * @mbg.generated
     */
    public void setIsSub(Boolean isSub) {
        this.isSub = isSub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.ficti
     *
     * @return the value of eb_store_product.ficti
     *
     * @mbg.generated
     */
    public Integer getFicti() {
        return ficti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.ficti
     *
     * @param ficti the value for eb_store_product.ficti
     *
     * @mbg.generated
     */
    public void setFicti(Integer ficti) {
        this.ficti = ficti;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.browse
     *
     * @return the value of eb_store_product.browse
     *
     * @mbg.generated
     */
    public Integer getBrowse() {
        return browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.browse
     *
     * @param browse the value for eb_store_product.browse
     *
     * @mbg.generated
     */
    public void setBrowse(Integer browse) {
        this.browse = browse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.code_path
     *
     * @return the value of eb_store_product.code_path
     *
     * @mbg.generated
     */
    public String getCodePath() {
        return codePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.code_path
     *
     * @param codePath the value for eb_store_product.code_path
     *
     * @mbg.generated
     */
    public void setCodePath(String codePath) {
        this.codePath = codePath == null ? null : codePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.soure_link
     *
     * @return the value of eb_store_product.soure_link
     *
     * @mbg.generated
     */
    public String getSoureLink() {
        return soureLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.soure_link
     *
     * @param soureLink the value for eb_store_product.soure_link
     *
     * @mbg.generated
     */
    public void setSoureLink(String soureLink) {
        this.soureLink = soureLink == null ? null : soureLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.video_link
     *
     * @return the value of eb_store_product.video_link
     *
     * @mbg.generated
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.video_link
     *
     * @param videoLink the value for eb_store_product.video_link
     *
     * @mbg.generated
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.temp_id
     *
     * @return the value of eb_store_product.temp_id
     *
     * @mbg.generated
     */
    public Integer getTempId() {
        return tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.temp_id
     *
     * @param tempId the value for eb_store_product.temp_id
     *
     * @mbg.generated
     */
    public void setTempId(Integer tempId) {
        this.tempId = tempId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.spec_type
     *
     * @return the value of eb_store_product.spec_type
     *
     * @mbg.generated
     */
    public Boolean getSpecType() {
        return specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.spec_type
     *
     * @param specType the value for eb_store_product.spec_type
     *
     * @mbg.generated
     */
    public void setSpecType(Boolean specType) {
        this.specType = specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.activity
     *
     * @return the value of eb_store_product.activity
     *
     * @mbg.generated
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.activity
     *
     * @param activity the value for eb_store_product.activity
     *
     * @mbg.generated
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.flat_pattern
     *
     * @return the value of eb_store_product.flat_pattern
     *
     * @mbg.generated
     */
    public String getFlatPattern() {
        return flatPattern;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.flat_pattern
     *
     * @param flatPattern the value for eb_store_product.flat_pattern
     *
     * @mbg.generated
     */
    public void setFlatPattern(String flatPattern) {
        this.flatPattern = flatPattern == null ? null : flatPattern.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_store_product.is_recycle
     *
     * @return the value of eb_store_product.is_recycle
     *
     * @mbg.generated
     */
    public Boolean getIsRecycle() {
        return isRecycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_store_product.is_recycle
     *
     * @param isRecycle the value for eb_store_product.is_recycle
     *
     * @mbg.generated
     */
    public void setIsRecycle(Boolean isRecycle) {
        this.isRecycle = isRecycle;
    }
}