package mall.pojo;

import java.util.Date;

public class EbSystemAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.roles
     *
     * @mbg.generated
     */
    private String roles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.login_count
     *
     * @mbg.generated
     */
    private Integer loginCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.is_del
     *
     * @mbg.generated
     */
    private Boolean isDel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_admin.is_sms
     *
     * @mbg.generated
     */
    private Boolean isSms;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    public EbSystemAdmin(Short id, String account, String pwd, String realName, String roles, String lastIp, Date updateTime, Date createTime, Integer loginCount, Byte level, Boolean status, Boolean isDel, String phone, Boolean isSms) {
        this.id = id;
        this.account = account;
        this.pwd = pwd;
        this.realName = realName;
        this.roles = roles;
        this.lastIp = lastIp;
        this.updateTime = updateTime;
        this.createTime = createTime;
        this.loginCount = loginCount;
        this.level = level;
        this.status = status;
        this.isDel = isDel;
        this.phone = phone;
        this.isSms = isSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    public EbSystemAdmin() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.id
     *
     * @return the value of eb_system_admin.id
     *
     * @mbg.generated
     */
    public short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.id
     *
     * @param id the value for eb_system_admin.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.account
     *
     * @return the value of eb_system_admin.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.account
     *
     * @param account the value for eb_system_admin.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.pwd
     *
     * @return the value of eb_system_admin.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.pwd
     *
     * @param pwd the value for eb_system_admin.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.real_name
     *
     * @return the value of eb_system_admin.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.real_name
     *
     * @param realName the value for eb_system_admin.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.roles
     *
     * @return the value of eb_system_admin.roles
     *
     * @mbg.generated
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.roles
     *
     * @param roles the value for eb_system_admin.roles
     *
     * @mbg.generated
     */
    public void setRoles(String roles) {
        this.roles = roles == null ? null : roles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.last_ip
     *
     * @return the value of eb_system_admin.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.last_ip
     *
     * @param lastIp the value for eb_system_admin.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.update_time
     *
     * @return the value of eb_system_admin.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.update_time
     *
     * @param updateTime the value for eb_system_admin.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.create_time
     *
     * @return the value of eb_system_admin.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.create_time
     *
     * @param createTime the value for eb_system_admin.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.login_count
     *
     * @return the value of eb_system_admin.login_count
     *
     * @mbg.generated
     */
    public Integer getLoginCount() {
        return loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.login_count
     *
     * @param loginCount the value for eb_system_admin.login_count
     *
     * @mbg.generated
     */
    public void setLoginCount(Integer loginCount) {
        this.loginCount = loginCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.level
     *
     * @return the value of eb_system_admin.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.level
     *
     * @param level the value for eb_system_admin.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.status
     *
     * @return the value of eb_system_admin.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.status
     *
     * @param status the value for eb_system_admin.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.is_del
     *
     * @return the value of eb_system_admin.is_del
     *
     * @mbg.generated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.is_del
     *
     * @param isDel the value for eb_system_admin.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.phone
     *
     * @return the value of eb_system_admin.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.phone
     *
     * @param phone the value for eb_system_admin.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_admin.is_sms
     *
     * @return the value of eb_system_admin.is_sms
     *
     * @mbg.generated
     */
    public Boolean getIsSms() {
        return isSms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_admin.is_sms
     *
     * @param isSms the value for eb_system_admin.is_sms
     *
     * @mbg.generated
     */
    public void setIsSms(Boolean isSms) {
        this.isSms = isSms;
    }
}