package mall.pojo;

import java.util.Date;

public class EbSystemFormTemp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.info
     *
     * @mbg.generated
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_form_temp.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    public EbSystemFormTemp(Integer id, String name, String info, Date createTime, Date updateTime, String content) {
        this.id = id;
        this.name = name;
        this.info = info;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    public EbSystemFormTemp() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.id
     *
     * @return the value of eb_system_form_temp.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.id
     *
     * @param id the value for eb_system_form_temp.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.name
     *
     * @return the value of eb_system_form_temp.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.name
     *
     * @param name the value for eb_system_form_temp.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.info
     *
     * @return the value of eb_system_form_temp.info
     *
     * @mbg.generated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.info
     *
     * @param info the value for eb_system_form_temp.info
     *
     * @mbg.generated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.create_time
     *
     * @return the value of eb_system_form_temp.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.create_time
     *
     * @param createTime the value for eb_system_form_temp.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.update_time
     *
     * @return the value of eb_system_form_temp.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.update_time
     *
     * @param updateTime the value for eb_system_form_temp.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_form_temp.content
     *
     * @return the value of eb_system_form_temp.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_form_temp.content
     *
     * @param content the value for eb_system_form_temp.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}