package mall.pojo;

import java.util.Date;

public class EbSystemRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.role_name
     *
     * @mbg.generated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_system_role.rules
     *
     * @mbg.generated
     */
    private String rules;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    public EbSystemRole(Integer id, String roleName, Byte level, Boolean status, Date createTime, Date updateTime, String rules) {
        this.id = id;
        this.roleName = roleName;
        this.level = level;
        this.status = status;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.rules = rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    public EbSystemRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.id
     *
     * @return the value of eb_system_role.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.id
     *
     * @param id the value for eb_system_role.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.role_name
     *
     * @return the value of eb_system_role.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.role_name
     *
     * @param roleName the value for eb_system_role.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.level
     *
     * @return the value of eb_system_role.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.level
     *
     * @param level the value for eb_system_role.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.status
     *
     * @return the value of eb_system_role.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.status
     *
     * @param status the value for eb_system_role.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.create_time
     *
     * @return the value of eb_system_role.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.create_time
     *
     * @param createTime the value for eb_system_role.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.update_time
     *
     * @return the value of eb_system_role.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.update_time
     *
     * @param updateTime the value for eb_system_role.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_system_role.rules
     *
     * @return the value of eb_system_role.rules
     *
     * @mbg.generated
     */
    public String getRules() {
        return rules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_system_role.rules
     *
     * @param rules the value for eb_system_role.rules
     *
     * @mbg.generated
     */
    public void setRules(String rules) {
        this.rules = rules == null ? null : rules.trim();
    }
}