package mall.pojo;

import com.baomidou.mybatisplus.annotation.TableField;

import java.math.BigDecimal;
import java.util.Date;

public class EbUser {
    public String getRoles() {
        return roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    @TableField(exist = false)
    private  String roles ;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.pwd
     *
     * @mbg.generated
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.real_name
     *
     * @mbg.generated
     */
    private String realName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.birthday
     *
     * @mbg.generated
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.card_id
     *
     * @mbg.generated
     */
    private String cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.partner_id
     *
     * @mbg.generated
     */
    private Integer partnerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.group_id
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.tag_id
     *
     * @mbg.generated
     */
    private String tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.avatar
     *
     * @mbg.generated
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.add_ip
     *
     * @mbg.generated
     */
    private String addIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.last_ip
     *
     * @mbg.generated
     */
    private String lastIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.now_money
     *
     * @mbg.generated
     */
    private BigDecimal nowMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.brokerage_price
     *
     * @mbg.generated
     */
    private BigDecimal brokeragePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.integral
     *
     * @mbg.generated
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.experience
     *
     * @mbg.generated
     */
    private Integer experience;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.sign_num
     *
     * @mbg.generated
     */
    private Integer signNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.level
     *
     * @mbg.generated
     */
    private Byte level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_uid
     *
     * @mbg.generated
     */
    private Integer spreadUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_time
     *
     * @mbg.generated
     */
    private Date spreadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.user_type
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.is_promoter
     *
     * @mbg.generated
     */
    private Boolean isPromoter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.pay_count
     *
     * @mbg.generated
     */
    private Integer payCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.spread_count
     *
     * @mbg.generated
     */
    private Integer spreadCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.addres
     *
     * @mbg.generated
     */
    private String addres;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.adminid
     *
     * @mbg.generated
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.login_type
     *
     * @mbg.generated
     */
    private String loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.last_login_time
     *
     * @mbg.generated
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.clean_time
     *
     * @mbg.generated
     */
    private Date cleanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.subscribe
     *
     * @mbg.generated
     */
    private Byte subscribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.subscribe_time
     *
     * @mbg.generated
     */
    private Date subscribeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.sex
     *
     * @mbg.generated
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.country
     *
     * @mbg.generated
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_user.promoter_time
     *
     * @mbg.generated
     */
    private Date promoterTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    public EbUser(Integer uid, String account, String pwd, String realName, String birthday, String cardId, String mark, Integer partnerId, String groupId, String tagId, String nickname, String avatar, String phone, String addIp, String lastIp, BigDecimal nowMoney, BigDecimal brokeragePrice, Integer integral, Integer experience, Integer signNum, Boolean status, Byte level, Integer spreadUid, Date spreadTime, String userType, Boolean isPromoter, Integer payCount, Integer spreadCount, String addres, Integer adminid, String loginType, Date createTime, Date updateTime, Date lastLoginTime, Date cleanTime, String path, Byte subscribe, Date subscribeTime, Boolean sex, String country, Date promoterTime) {
        this.uid = uid;
        this.account = account;
        this.pwd = pwd;
        this.realName = realName;
        this.birthday = birthday;
        this.cardId = cardId;
        this.mark = mark;
        this.partnerId = partnerId;
        this.groupId = groupId;
        this.tagId = tagId;
        this.nickname = nickname;
        this.avatar = avatar;
        this.phone = phone;
        this.addIp = addIp;
        this.lastIp = lastIp;
        this.nowMoney = nowMoney;
        this.brokeragePrice = brokeragePrice;
        this.integral = integral;
        this.experience = experience;
        this.signNum = signNum;
        this.status = status;
        this.level = level;
        this.spreadUid = spreadUid;
        this.spreadTime = spreadTime;
        this.userType = userType;
        this.isPromoter = isPromoter;
        this.payCount = payCount;
        this.spreadCount = spreadCount;
        this.addres = addres;
        this.adminid = adminid;
        this.loginType = loginType;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.lastLoginTime = lastLoginTime;
        this.cleanTime = cleanTime;
        this.path = path;
        this.subscribe = subscribe;
        this.subscribeTime = subscribeTime;
        this.sex = sex;
        this.country = country;
        this.promoterTime = promoterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    public EbUser() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.uid
     *
     * @return the value of eb_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.uid
     *
     * @param uid the value for eb_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.account
     *
     * @return the value of eb_user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.account
     *
     * @param account the value for eb_user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.pwd
     *
     * @return the value of eb_user.pwd
     *
     * @mbg.generated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.pwd
     *
     * @param pwd the value for eb_user.pwd
     *
     * @mbg.generated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.real_name
     *
     * @return the value of eb_user.real_name
     *
     * @mbg.generated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.real_name
     *
     * @param realName the value for eb_user.real_name
     *
     * @mbg.generated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.birthday
     *
     * @return the value of eb_user.birthday
     *
     * @mbg.generated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.birthday
     *
     * @param birthday the value for eb_user.birthday
     *
     * @mbg.generated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.card_id
     *
     * @return the value of eb_user.card_id
     *
     * @mbg.generated
     */
    public String getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.card_id
     *
     * @param cardId the value for eb_user.card_id
     *
     * @mbg.generated
     */
    public void setCardId(String cardId) {
        this.cardId = cardId == null ? null : cardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.mark
     *
     * @return the value of eb_user.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.mark
     *
     * @param mark the value for eb_user.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.partner_id
     *
     * @return the value of eb_user.partner_id
     *
     * @mbg.generated
     */
    public Integer getPartnerId() {
        return partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.partner_id
     *
     * @param partnerId the value for eb_user.partner_id
     *
     * @mbg.generated
     */
    public void setPartnerId(Integer partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.group_id
     *
     * @return the value of eb_user.group_id
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.group_id
     *
     * @param groupId the value for eb_user.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.tag_id
     *
     * @return the value of eb_user.tag_id
     *
     * @mbg.generated
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.tag_id
     *
     * @param tagId the value for eb_user.tag_id
     *
     * @mbg.generated
     */
    public void setTagId(String tagId) {
        this.tagId = tagId == null ? null : tagId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.nickname
     *
     * @return the value of eb_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.nickname
     *
     * @param nickname the value for eb_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.avatar
     *
     * @return the value of eb_user.avatar
     *
     * @mbg.generated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.avatar
     *
     * @param avatar the value for eb_user.avatar
     *
     * @mbg.generated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.phone
     *
     * @return the value of eb_user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.phone
     *
     * @param phone the value for eb_user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.add_ip
     *
     * @return the value of eb_user.add_ip
     *
     * @mbg.generated
     */
    public String getAddIp() {
        return addIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.add_ip
     *
     * @param addIp the value for eb_user.add_ip
     *
     * @mbg.generated
     */
    public void setAddIp(String addIp) {
        this.addIp = addIp == null ? null : addIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.last_ip
     *
     * @return the value of eb_user.last_ip
     *
     * @mbg.generated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.last_ip
     *
     * @param lastIp the value for eb_user.last_ip
     *
     * @mbg.generated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.now_money
     *
     * @return the value of eb_user.now_money
     *
     * @mbg.generated
     */
    public BigDecimal getNowMoney() {
        return nowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.now_money
     *
     * @param nowMoney the value for eb_user.now_money
     *
     * @mbg.generated
     */
    public void setNowMoney(BigDecimal nowMoney) {
        this.nowMoney = nowMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.brokerage_price
     *
     * @return the value of eb_user.brokerage_price
     *
     * @mbg.generated
     */
    public BigDecimal getBrokeragePrice() {
        return brokeragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.brokerage_price
     *
     * @param brokeragePrice the value for eb_user.brokerage_price
     *
     * @mbg.generated
     */
    public void setBrokeragePrice(BigDecimal brokeragePrice) {
        this.brokeragePrice = brokeragePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.integral
     *
     * @return the value of eb_user.integral
     *
     * @mbg.generated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.integral
     *
     * @param integral the value for eb_user.integral
     *
     * @mbg.generated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.experience
     *
     * @return the value of eb_user.experience
     *
     * @mbg.generated
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.experience
     *
     * @param experience the value for eb_user.experience
     *
     * @mbg.generated
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.sign_num
     *
     * @return the value of eb_user.sign_num
     *
     * @mbg.generated
     */
    public Integer getSignNum() {
        return signNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.sign_num
     *
     * @param signNum the value for eb_user.sign_num
     *
     * @mbg.generated
     */
    public void setSignNum(Integer signNum) {
        this.signNum = signNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.status
     *
     * @return the value of eb_user.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.status
     *
     * @param status the value for eb_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.level
     *
     * @return the value of eb_user.level
     *
     * @mbg.generated
     */
    public Byte getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.level
     *
     * @param level the value for eb_user.level
     *
     * @mbg.generated
     */
    public void setLevel(Byte level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_uid
     *
     * @return the value of eb_user.spread_uid
     *
     * @mbg.generated
     */
    public Integer getSpreadUid() {
        return spreadUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_uid
     *
     * @param spreadUid the value for eb_user.spread_uid
     *
     * @mbg.generated
     */
    public void setSpreadUid(Integer spreadUid) {
        this.spreadUid = spreadUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_time
     *
     * @return the value of eb_user.spread_time
     *
     * @mbg.generated
     */
    public Date getSpreadTime() {
        return spreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_time
     *
     * @param spreadTime the value for eb_user.spread_time
     *
     * @mbg.generated
     */
    public void setSpreadTime(Date spreadTime) {
        this.spreadTime = spreadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.user_type
     *
     * @return the value of eb_user.user_type
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.user_type
     *
     * @param userType the value for eb_user.user_type
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.is_promoter
     *
     * @return the value of eb_user.is_promoter
     *
     * @mbg.generated
     */
    public Boolean getIsPromoter() {
        return isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.is_promoter
     *
     * @param isPromoter the value for eb_user.is_promoter
     *
     * @mbg.generated
     */
    public void setIsPromoter(Boolean isPromoter) {
        this.isPromoter = isPromoter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.pay_count
     *
     * @return the value of eb_user.pay_count
     *
     * @mbg.generated
     */
    public Integer getPayCount() {
        return payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.pay_count
     *
     * @param payCount the value for eb_user.pay_count
     *
     * @mbg.generated
     */
    public void setPayCount(Integer payCount) {
        this.payCount = payCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.spread_count
     *
     * @return the value of eb_user.spread_count
     *
     * @mbg.generated
     */
    public Integer getSpreadCount() {
        return spreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.spread_count
     *
     * @param spreadCount the value for eb_user.spread_count
     *
     * @mbg.generated
     */
    public void setSpreadCount(Integer spreadCount) {
        this.spreadCount = spreadCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.addres
     *
     * @return the value of eb_user.addres
     *
     * @mbg.generated
     */
    public String getAddres() {
        return addres;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.addres
     *
     * @param addres the value for eb_user.addres
     *
     * @mbg.generated
     */
    public void setAddres(String addres) {
        this.addres = addres == null ? null : addres.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.adminid
     *
     * @return the value of eb_user.adminid
     *
     * @mbg.generated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.adminid
     *
     * @param adminid the value for eb_user.adminid
     *
     * @mbg.generated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.login_type
     *
     * @return the value of eb_user.login_type
     *
     * @mbg.generated
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.login_type
     *
     * @param loginType the value for eb_user.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.create_time
     *
     * @return the value of eb_user.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.create_time
     *
     * @param createTime the value for eb_user.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.update_time
     *
     * @return the value of eb_user.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.update_time
     *
     * @param updateTime the value for eb_user.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.last_login_time
     *
     * @return the value of eb_user.last_login_time
     *
     * @mbg.generated
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.last_login_time
     *
     * @param lastLoginTime the value for eb_user.last_login_time
     *
     * @mbg.generated
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.clean_time
     *
     * @return the value of eb_user.clean_time
     *
     * @mbg.generated
     */
    public Date getCleanTime() {
        return cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.clean_time
     *
     * @param cleanTime the value for eb_user.clean_time
     *
     * @mbg.generated
     */
    public void setCleanTime(Date cleanTime) {
        this.cleanTime = cleanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.path
     *
     * @return the value of eb_user.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.path
     *
     * @param path the value for eb_user.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.subscribe
     *
     * @return the value of eb_user.subscribe
     *
     * @mbg.generated
     */
    public Byte getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.subscribe
     *
     * @param subscribe the value for eb_user.subscribe
     *
     * @mbg.generated
     */
    public void setSubscribe(Byte subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.subscribe_time
     *
     * @return the value of eb_user.subscribe_time
     *
     * @mbg.generated
     */
    public Date getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.subscribe_time
     *
     * @param subscribeTime the value for eb_user.subscribe_time
     *
     * @mbg.generated
     */
    public void setSubscribeTime(Date subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.sex
     *
     * @return the value of eb_user.sex
     *
     * @mbg.generated
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.sex
     *
     * @param sex the value for eb_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.country
     *
     * @return the value of eb_user.country
     *
     * @mbg.generated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.country
     *
     * @param country the value for eb_user.country
     *
     * @mbg.generated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eb_user.promoter_time
     *
     * @return the value of eb_user.promoter_time
     *
     * @mbg.generated
     */
    public Date getPromoterTime() {
        return promoterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eb_user.promoter_time
     *
     * @param promoterTime the value for eb_user.promoter_time
     *
     * @mbg.generated
     */
    public void setPromoterTime(Date promoterTime) {
        this.promoterTime = promoterTime;
    }
}