package mall.mapper;

import java.util.List;
import mall.pojo.EbStoreProduct;
import mall.pojo.EbStoreProductExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbStoreProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    long countByExample(EbStoreProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int deleteByExample(EbStoreProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int insert(EbStoreProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int insertSelective(EbStoreProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    List<EbStoreProduct> selectByExampleWithRowbounds(EbStoreProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    List<EbStoreProduct> selectByExample(EbStoreProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    EbStoreProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbStoreProduct record, @Param("example") EbStoreProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbStoreProduct record, @Param("example") EbStoreProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbStoreProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_store_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbStoreProduct record);
}