package mall.mapper;

import java.util.List;
import mall.pojo.EbSystemFormTemp;
import mall.pojo.EbSystemFormTempExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbSystemFormTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    long countByExample(EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int deleteByExample(EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int insert(EbSystemFormTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int insertSelective(EbSystemFormTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    List<EbSystemFormTemp> selectByExampleWithBLOBsWithRowbounds(EbSystemFormTempExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    List<EbSystemFormTemp> selectByExampleWithBLOBs(EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    List<EbSystemFormTemp> selectByExampleWithRowbounds(EbSystemFormTempExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    List<EbSystemFormTemp> selectByExample(EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    EbSystemFormTemp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbSystemFormTemp record, @Param("example") EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EbSystemFormTemp record, @Param("example") EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbSystemFormTemp record, @Param("example") EbSystemFormTempExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbSystemFormTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EbSystemFormTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_form_temp
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemFormTemp record);
}