package mall.mapper;

import java.util.List;
import mall.pojo.EbSystemMenu;
import mall.pojo.EbSystemMenuExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbSystemMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    long countByExample(EbSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int deleteByExample(EbSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int insert(EbSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int insertSelective(EbSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    List<EbSystemMenu> selectByExampleWithRowbounds(EbSystemMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    List<EbSystemMenu> selectByExample(EbSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    EbSystemMenu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbSystemMenu record, @Param("example") EbSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbSystemMenu record, @Param("example") EbSystemMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbSystemMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemMenu record);
}