package mall.mapper;

import java.util.List;
import mall.pojo.EbSystemAdmin;
import mall.pojo.EbSystemAdminExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbSystemAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    long countByExample(EbSystemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int deleteByExample(EbSystemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int insert(EbSystemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int insertSelective(EbSystemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    List<EbSystemAdmin> selectByExampleWithRowbounds(EbSystemAdminExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    List<EbSystemAdmin> selectByExample(EbSystemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    EbSystemAdmin selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbSystemAdmin record, @Param("example") EbSystemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbSystemAdmin record, @Param("example") EbSystemAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbSystemAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_admin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemAdmin record);
}