package mall.mapper;

import java.util.List;
import mall.pojo.EbSystemRole;
import mall.pojo.EbSystemRoleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbSystemRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    long countByExample(EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int deleteByExample(EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int insert(EbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int insertSelective(EbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    List<EbSystemRole> selectByExampleWithBLOBsWithRowbounds(EbSystemRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    List<EbSystemRole> selectByExampleWithBLOBs(EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    List<EbSystemRole> selectByExampleWithRowbounds(EbSystemRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    List<EbSystemRole> selectByExample(EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    EbSystemRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbSystemRole record, @Param("example") EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") EbSystemRole record, @Param("example") EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbSystemRole record, @Param("example") EbSystemRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(EbSystemRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_system_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbSystemRole record);
}