package mall.mapper;

import java.util.List;
import mall.pojo.EbUser;
import mall.pojo.EbUserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EbUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    long countByExample(EbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int deleteByExample(EbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int insert(EbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int insertSelective(EbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    List<EbUser> selectByExampleWithRowbounds(EbUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    List<EbUser> selectByExample(EbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    EbUser selectByPrimaryKey(Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EbUser record, @Param("example") EbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EbUser record, @Param("example") EbUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EbUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eb_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EbUser record);
}